version: '3'

services:
  api:
    build: .
    container_name: pebble-crypto-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./app:/code/app  # For development - enables live code reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 